name: Pro Photo Services
favicon: null
layout_spectrum: 0.7987977773882449
typography_spectrum: 0.524662519339472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.30206805979833007
  lightness: 0.7432774824555963
  saturation: 0.8728958046995103
  rhythmicContrast: 0.6045389140490443
purpose: []
